FROM therecipe/qt:windows_64_static as qt

RUN apt-get update
RUN apt-get -y install git

WORKDIR /home/user/work/src/github.com/cfanatic/
RUN go get -v -d github.com/cfanatic/go-expensegui

RUN qtdeploy build windows github.com/cfanatic/go-expensegui
